/**
 * Core domain types for YouTube Dubbing
 * Following CONTEXT.md and docs/SPEC.md
 */

export interface Segment {
  id: string;
  startTime: number;     // in seconds
  endTime: number;       // in seconds
  duration: number;      // in seconds
  sourceText: string;
  translatedText?: string;
  speakerGender?: 'female' | 'male';
  voiceProfileId?: string;
  audioBlob?: Blob;
  audioUrl?: string;
}

export interface Transcript {
  videoId: string;
  sourceLanguage: string;
  targetLanguage?: string;
  segments: Segment[];
  isAutoGenerated?: boolean;
}

export interface CaptionTrack {
  baseUrl: string;
  languageCode: string;
  name?: string;
  kind?: 'asr' | string; // 'asr' = auto-generated speech recognition
  isTranslatable?: boolean;
}

export interface PlayerResponseCaptions {
  playerCaptionsTracklistRenderer?: {
    captionTracks?: Array<{
      baseUrl: string;
      name?: { simpleText?: string; runs?: Array<{ text: string }> };
      vssId?: string;
      languageCode: string;
      kind?: string;
      isTranslatable?: boolean;
    }>;
  };
}

/**
 * Voice profile for TTS synthesis.
 * Follows VoiceProfile contract from docs/SPEC.md and CONTEXT.md.
 */
export interface VoiceProfile {
  id: string;
  name: string;
  gender: 'female' | 'male';
  locale: string;
  provider: 'edge-tts' | 'elevenlabs' | 'web-speech';
  voiceKey: string;
  pitch?: string; // e.g. "+0Hz", "+5Hz" (SSML prosody pitch parameter)
  rate?: string;  // e.g. "+0%", "+10%" (SSML prosody rate parameter)
}
