/**
 * Core domain types for YouTube Dubbing
 * Following CONTEXT.md and docs/SPEC.md
 */

export interface Segment {
  id: string;
  startTime: number;     // in seconds
  endTime: number;       // in seconds
  duration: number;      // in seconds
  sourceText: string;
  translatedText?: string;
  speakerGender?: 'female' | 'male';
  voiceProfileId?: string;
  audioBlob?: Blob;
  audioUrl?: string;
}

export interface Transcript {
  videoId: string;
  sourceLanguage: string;
  targetLanguage?: string;
  segments: Segment[];
  isAutoGenerated?: boolean;
}

export interface CaptionTrack {
  baseUrl: string;
  languageCode: string;
  name?: string;
  kind?: 'asr' | string; // 'asr' = auto-generated speech recognition
  isTranslatable?: boolean;
}

export interface PlayerResponseCaptions {
  captions?: {
    playerCaptionsTracklistRenderer?: {
      captionTracks?: Array<{
        baseUrl: string;
        name?: { simpleText?: string; runs?: Array<{ text: string }> };
        vssId?: string;
        languageCode: string;
        kind?: string;
        isTranslatable?: boolean;
      }>;
    };
  };
  playerCaptionsTracklistRenderer?: {
    captionTracks?: Array<{
      baseUrl: string;
      name?: { simpleText?: string; runs?: Array<{ text: string }> };
      vssId?: string;
      languageCode: string;
      kind?: string;
      isTranslatable?: boolean;
    }>;
  };
}

/**
 * Voice profile for TTS synthesis.
 * Follows VoiceProfile contract from docs/SPEC.md and CONTEXT.md.
 */
export interface VoiceProfile {
  id: string;
  name: string;
  gender: 'female' | 'male';
  locale: string;
  provider: 'edge-tts' | 'elevenlabs' | 'web-speech';
  voiceKey: string;
  pitch?: string; // e.g. "+0Hz", "+5Hz" (SSML prosody pitch parameter)
  rate?: string;  // e.g. "+0%", "+10%" (SSML prosody rate parameter)
}

// ---------------------------------------------------------------------------
// Orchestrator domain contracts (Issue #6)
// ---------------------------------------------------------------------------

/**
 * Configuration for the DubbingOrchestrator.
 */
export interface OrchestratorConfig {
  /** BCP-47 language code for the target dubbing language (e.g. "vi"). */
  targetLanguage: string;
  /** Seconds ahead of playhead to pre-synthesize TTS audio. Default: 60. */
  lookaheadSeconds?: number;
  /** Volume fraction to duck to during speech (0–1). Default: 0.2. */
  duckLevel?: number;
  /** Whether automatic multi-speaker diarization is enabled. Default: false. */
  diarizationEnabled?: boolean;
  /** Default fallback voice profile id. */
  defaultVoice?: string;
  /** Voice profile id to use for female speakers. */
  femaleVoice?: string;
  /** Voice profile id to use for male speakers. */
  maleVoice?: string;
}

/**
 * Runtime status of the DubbingOrchestrator.
 */
export type OrchestratorStatus =
  | 'idle'
  | 'ready'
  | 'playing'
  | 'paused'
  | 'seeking'
  | 'destroyed';

/**
 * Observable state snapshot returned by DubbingOrchestrator.getState().
 */
export interface OrchestratorState {
  status: OrchestratorStatus;
  targetLanguage: string;
  /** Current host video playback rate (e.g. 1.0, 1.5, 2.0). */
  playbackRate: number;
  /** Currently active segment id, if any. */
  activeSegmentId: string | null;
  /** Whether multi-speaker diarization is active. */
  diarizationEnabled?: boolean;
  /** Currently resolved/active voice id for the active segment or system. */
  activeVoiceId?: string;
}

/**
 * Public contract for the DubbingOrchestrator (primary seam from docs/SPEC.md).
 */
export interface DubbingOrchestrator {
  init(videoId: string, transcript: Transcript, config: OrchestratorConfig): Promise<void>;
  handleTimeUpdate(currentTime: number): void;
  handleSeek(newTime: number): void;
  handleRateChange(newRate: number): void;
  handlePlay(): void;
  handlePause(): void;
  setTargetLanguage(languageCode: string): Promise<void>;
  setVoiceProfile?(profile: VoiceProfile | string): void;
  setDuckLevel?(duckLevel: number): void;
  getActiveSegment?(): Segment | null;
  isDucked?(): boolean;
  setDiarizationEnabled?(enabled: boolean): void;
  isDiarizationEnabled?(): boolean;
  primeInitialLookahead?(currentTime: number): Promise<void>;
  getState(): OrchestratorState;
  destroy(): void;
}

